/**
 * AsiaPower — Site Configuration
 */
const ASIAPOWER = {
  company: 'AsiaPower',
  siteUrl: '',
  tagline: 'Global Powertrain Sourcing Platform',
  logo: 'assets/logo.png',
  logoSrcSet: 'assets/logo.png 256w, assets/logo@2x.png 512w, assets/logo@3x.png 768w',
  logoSizes: '(max-width: 768px) 46vw, 320px',
  whatsapp: '8618603773077',
  whatsappDisplay: '+86 186 0377 3077',
  whatsappMessage: 'Hello AsiaPower, I would like to enquire about powertrain sourcing for export.',
  email: 'weylonhui@gmail.com',
  supplierEmail: 'weylonhui@gmail.com',
  offices: {
    china: {
      label: 'China Office',
      address: 'South Third Ring Road & Shangdu Road, Zhengzhou, Henan, China',
      flag: '🇨🇳',
    },
    ghana: {
      label: 'Ghana Office',
      address: 'No.2 Flower Street, Tabora, Accra, Ghana',
      flag: '🇬🇭',
    },
  },
  nav: [
    { href: 'index.html', label: 'Home', id: 'home' },
    { href: 'brands.html', label: 'Brands', id: 'brands' },
    { href: 'supplier-portal.html', label: 'Supplier Portal', id: 'supplier' },
    { href: 'contact.html', label: 'Contact', id: 'contact' },
  ],
  seoProducts: [
    { label: 'Engines', href: 'engines/' },
    { label: 'Gearboxes', href: 'gearboxes/' },
    { label: 'Chassis Parts', href: 'chassis-parts/' },
    { label: 'Half-Cuts', href: 'half-cuts/' },
  ],
  seoEngines: [
    { code: '1NZ-FE', slug: 'toyota-1nz-fe' },
    { code: '2NZ-FE', slug: 'toyota-2nz-fe' },
    { code: '1ZZ-FE', slug: 'toyota-1zz-fe' },
    { code: '2TR-FE', slug: 'toyota-2tr-fe' },
    { code: '1KD-FTV', slug: 'toyota-1kd-ftv' },
    { code: '2KD-FTV', slug: 'toyota-2kd-ftv' },
    { code: 'G4KD', slug: 'hyundai-g4kd' },
    { code: 'G4NA', slug: 'hyundai-g4na' },
    { code: 'HR15DE', slug: 'nissan-hr15de' },
    { code: 'HR16DE', slug: 'nissan-hr16de' },
    { code: 'QR25DE', slug: 'nissan-qr25de' },
    { code: 'K24A', slug: 'honda-k24a' },
  ],
  seoBrands: [
    { name: 'Toyota', href: 'brands/toyota.html' },
    { name: 'Hyundai', href: 'brands/hyundai.html' },
    { name: 'Kia', href: 'brands/kia.html' },
    { name: 'Nissan', href: 'brands/nissan.html' },
    { name: 'Honda', href: 'brands/honda.html' },
    { name: 'BYD', href: 'brands/byd.html' },
    { name: 'Geely', href: 'brands/geely.html' },
    { name: 'Chery', href: 'brands/chery.html' },
  ],
  stats: [
    { value: '15+', label: 'Years in Trade' },
    { value: '6,000+', label: 'Units Exported' },
    { value: '5', label: 'Global Regions' },
    { value: '200+', label: 'Verified Suppliers' },
  ],
  homepageBrands: [
    'toyota', 'honda', 'nissan', 'ford', 'chevrolet', 'volkswagen',
    'hyundai', 'kia', 'byd', 'mercedes-benz', 'bmw', 'geely', 'chery',
  ],
  categories: [
    { href: 'brands.html', title: 'Brand Directory', count: '50+', desc: 'Start by vehicle brand', icon: 'network' },
    { href: 'engines/', title: 'Used Engines', count: '5000+', desc: 'Petrol, diesel & hybrid', icon: 'engine' },
    { href: 'gearboxes/', title: 'Used Gearboxes', count: '1000+', desc: 'Auto, manual & 4WD', icon: 'gearbox' },
    { href: 'chassis-parts/', title: 'Chassis Parts', count: '500+', desc: 'Suspension & steering', icon: 'diesel' },
    { href: 'half-cuts/', title: 'Half-Cuts', count: '500+', desc: 'Front, rear & nose cuts', icon: '4wd' },
    { href: 'contact.html', title: 'Bulk Orders', count: 'FOB/CIF', desc: 'Container shipments', icon: 'shipping' },
  ],
  featuredBrandSlugs: [
    'toyota', 'hyundai', 'kia', 'honda', 'nissan', 'byd',
    'ford', 'chevrolet', 'volkswagen', 'mercedes-benz', 'bmw',
  ],
  brandsDirectory: [
    { name: 'Toyota', slug: 'toyota', landingPage: 'brands/toyota.html', engineModels: ['1NZ-FE', '2NZ-FE', '1ZZ-FE', '3ZZ-FE', '2AZ-FE', '1AZ-FE', '2ZR-FE', '3ZR-FE', '2TR-FE', '1GR-FE', '2GR-FE', '1KD-FTV', '2KD-FTV'] },
    { name: 'Lexus', slug: 'lexus', landingPage: 'brands/lexus.html', engineModels: ['2GR-FE', '1GR-FE', '1UR-FSE', '2UR-FSE', '3UR-FBE', '1NZ-FE', '2AR-FE', '8AR-FTS'] },
    { name: 'Honda', slug: 'honda', landingPage: 'brands/honda.html', engineModels: ['L13A', 'L15A', 'L15B', 'R18A', 'R20A', 'K20A', 'K24A', 'J30A', 'J35A'] },
    { name: 'Acura', slug: 'acura', landingPage: 'brands/acura.html', engineModels: ['K24A', 'J35A', 'R20A', 'L15B', 'J30A', 'K20A'] },
    { name: 'Nissan', slug: 'nissan', landingPage: 'brands/nissan.html', engineModels: ['GA16DE', 'QG15DE', 'QG18DE', 'HR15DE', 'HR16DE', 'MR18DE', 'MR20DE', 'QR20DE', 'QR25DE', 'VQ25DE', 'VQ35DE'] },
    { name: 'Infiniti', slug: 'infiniti', landingPage: 'brands/infiniti.html', engineModels: ['VQ35DE', 'VQ25DE', 'QR25DE', 'HR16DE', 'MR20DE', 'VK56VD'] },
    { name: 'Mazda', slug: 'mazda', landingPage: 'brands/mazda.html', engineModels: ['ZJ', 'ZY', 'ZM', 'LF', 'L3', 'PE-VPS', 'PY-VPS'] },
    { name: 'Mitsubishi', slug: 'mitsubishi', landingPage: 'brands/mitsubishi.html', engineModels: ['4G13', '4G15', '4G18', '4G63', '4G64', '4G69', '4B10', '4B11', '4B12'] },
    { name: 'Subaru', slug: 'subaru', landingPage: 'brands/subaru.html', engineModels: ['EJ15', 'EJ20', 'EJ25', 'FB20', 'FB25', 'FA20'] },
    { name: 'Suzuki', slug: 'suzuki', landingPage: 'brands/suzuki.html', engineModels: ['F10A', 'G13B', 'G16B', 'M13A', 'M15A', 'M16A', 'J20A'] },
    { name: 'Daihatsu', slug: 'daihatsu', landingPage: 'brands/daihatsu.html', engineModels: ['EF-VE', 'EJ-VE', 'K3-VE', '3SZ-VE'] },
    { name: 'Hyundai', slug: 'hyundai', landingPage: 'brands/hyundai.html', engineModels: ['G4FA', 'G4FC', 'G4FG', 'G4GC', 'G4KD', 'G4KE', 'G4KJ', 'G4KH', 'G4NA', 'G4NB', 'G4NC', 'G6BA', 'G6EA', 'G6DB', 'G6DH'] },
    { name: 'Kia', slug: 'kia', landingPage: 'brands/kia.html', engineModels: ['G4FA', 'G4FC', 'G4FG', 'G4GC', 'G4KD', 'G4KE', 'G4KJ', 'G4KH', 'G4NA', 'G4NB', 'G4NC', 'G6BA', 'G6EA', 'G6DB', 'G6DH'] },
    { name: 'Genesis', slug: 'genesis', landingPage: 'brands/genesis.html', engineModels: ['G4KH', 'G6DH', 'G4NA', 'G4KE', 'G4KJ', 'G6DB'] },
    { name: 'BYD', slug: 'byd', landingPage: 'brands/byd.html', engineModels: ['BYD371QA', 'BYD473QB', 'BYD476ZQA', 'BYD483QA', 'BYD487ZQA'] },
    { name: 'Geely', slug: 'geely', landingPage: 'brands/geely.html', engineModels: ['JL4G15', 'JL4G18', 'JLB-4G13T', 'JLE-4G18TD'] },
    { name: 'Zeekr', slug: 'zeekr', landingPage: 'brands/zeekr.html', engineModels: ['JL4G15', 'JL4G18', 'JLB-4G13T', 'JLE-4G18TD'] },
    { name: 'Lynk & Co', slug: 'lynk-co', landingPage: 'brands/lynk-co.html', engineModels: ['JL4G15', 'JL4G18', 'JLB-4G13T', 'JLE-4G18TD'] },
    { name: 'Geometry', slug: 'geometry', landingPage: 'brands/geometry.html', engineModels: ['JL4G15', 'JL4G18', 'JLB-4G13T', 'JLE-4G18TD'] },
    { name: 'Chery', slug: 'chery', landingPage: 'brands/chery.html', engineModels: ['SQR372', 'SQR472', 'SQR477', 'E4G15', 'E4G16', 'SQRE4T15C'] },
    { name: 'Exeed', slug: 'exeed', landingPage: 'brands/exeed.html', engineModels: ['SQR372', 'SQR472', 'SQR477', 'E4G15', 'E4G16', 'SQRE4T15C'] },
    { name: 'Jetour', slug: 'jetour', landingPage: 'brands/jetour.html', engineModels: ['SQR372', 'SQR472', 'SQR477', 'E4G15', 'E4G16', 'SQRE4T15C'] },
    { name: 'Omoda', slug: 'omoda', landingPage: 'brands/omoda.html', engineModels: ['SQR372', 'SQR472', 'SQR477', 'E4G15', 'E4G16', 'SQRE4T15C'] },
    { name: 'Jaecoo', slug: 'jaecoo', landingPage: 'brands/jaecoo.html', engineModels: ['SQR372', 'SQR472', 'SQR477', 'E4G15', 'E4G16', 'SQRE4T15C'] },
    { name: 'Great Wall', slug: 'great-wall', landingPage: 'brands/great-wall.html', engineModels: ['GW4G15', 'GW4G15T', 'GW4B15A', 'GW4C20', 'GW4N20'] },
    { name: 'Haval', slug: 'haval', landingPage: 'brands/haval.html', engineModels: ['GW4G15', 'GW4G15T', 'GW4B15A', 'GW4C20', 'GW4N20'] },
    { name: 'Tank', slug: 'tank', landingPage: 'brands/tank.html', engineModels: ['GW4G15', 'GW4G15T', 'GW4B15A', 'GW4C20', 'GW4N20'] },
    { name: 'Ora', slug: 'ora', landingPage: 'brands/ora.html', engineModels: ['GW4G15', 'GW4G15T', 'GW4B15A', 'GW4C20', 'GW4N20'] },
    { name: 'MG', slug: 'mg', landingPage: 'brands/mg.html', engineModels: ['15S4C', '18K4G', '20T4E5', 'NSE Major', 'SGE Plus'] },
    { name: 'Roewe', slug: 'roewe', landingPage: 'brands/roewe.html', engineModels: ['15S4C', '18K4G', '20T4E5', 'NSE Major', 'SGE Plus'] },
    { name: 'GAC', slug: 'gac', landingPage: 'brands/gac.html', engineModels: ['4G15', '4G18', '4A91', '4A92', '4B11', 'SQRE4T15C', 'E4G16'] },
    { name: 'JAC', slug: 'jac', landingPage: 'brands/jac.html', engineModels: ['4G15', '4G18', '4A91', '4A92', '4B11', 'SQRE4T15C', 'E4G16'] },
    { name: 'Dongfeng', slug: 'dongfeng', landingPage: 'brands/dongfeng.html', engineModels: ['4G15', '4G18', '4A91', '4A92', '4B11', 'SQRE4T15C', 'E4G16'] },
    { name: 'FAW', slug: 'faw', landingPage: 'brands/faw.html', engineModels: ['4G15', '4G18', '4A91', '4A92', '4B11', 'SQRE4T15C', 'E4G16'] },
    { name: 'Foton', slug: 'foton', landingPage: 'brands/foton.html', engineModels: ['4G15', '4G18', '4A91', '4A92', '4B11', 'SQRE4T15C', 'E4G16'] },
    { name: 'JMC', slug: 'jmc', landingPage: 'brands/jmc.html', engineModels: ['4G15', '4G18', '4A91', '4A92', '4B11', 'SQRE4T15C', 'E4G16'] },
    { name: 'Maxus', slug: 'maxus', landingPage: 'brands/maxus.html', engineModels: ['4G15', '4G18', '4A91', '4A92', '4B11', 'SQRE4T15C', 'E4G16'] },
    { name: 'Ford', slug: 'ford', landingPage: 'brands/ford.html', engineModels: ['Duratec 1.5', 'Duratec 2.0', 'EcoBoost 1.5', 'EcoBoost 2.0', 'EcoBoost 2.3'] },
    { name: 'Lincoln', slug: 'lincoln', landingPage: 'brands/lincoln.html', engineModels: ['Duratec 1.5', 'Duratec 2.0', 'EcoBoost 1.5', 'EcoBoost 2.0', 'EcoBoost 2.3'] },
    { name: 'Chevrolet', slug: 'chevrolet', landingPage: 'brands/chevrolet.html', engineModels: ['L2B', 'F16D3', 'F18D4', 'LE5', 'LAF', 'LUJ'] },
    { name: 'GMC', slug: 'gmc', landingPage: 'brands/gmc.html', engineModels: ['L2B', 'F16D3', 'F18D4', 'LE5', 'LAF', 'LUJ'] },
    { name: 'Buick', slug: 'buick', landingPage: 'brands/buick.html', engineModels: ['L2B', 'F16D3', 'F18D4', 'LE5', 'LAF', 'LUJ'] },
    { name: 'Cadillac', slug: 'cadillac', landingPage: 'brands/cadillac.html', engineModels: ['L2B', 'F16D3', 'F18D4', 'LE5', 'LAF', 'LUJ'] },
    { name: 'Volkswagen', slug: 'volkswagen', landingPage: 'brands/volkswagen.html', engineModels: ['EA111', 'EA211', 'EA113', 'EA888', 'CAYC', 'CBZ', 'CDA', 'BWA'] },
    { name: 'Audi', slug: 'audi', landingPage: 'brands/audi.html', engineModels: ['EA111', 'EA211', 'EA113', 'EA888', 'CAYC', 'CBZ', 'CDA', 'BWA'] },
    { name: 'Skoda', slug: 'skoda', landingPage: 'brands/skoda.html', engineModels: ['EA111', 'EA211', 'EA113', 'EA888', 'CAYC', 'CBZ', 'CDA', 'BWA'] },
    { name: 'Seat', slug: 'seat', landingPage: 'brands/seat.html', engineModels: ['EA111', 'EA211', 'EA113', 'EA888', 'CAYC', 'CBZ', 'CDA', 'BWA'] },
    { name: 'Mercedes-Benz', slug: 'mercedes-benz', landingPage: 'brands/mercedes-benz.html', engineModels: ['M111', 'M112', 'M113', 'M271', 'M272', 'M274', 'M276'] },
    { name: 'BMW', slug: 'bmw', landingPage: 'brands/bmw.html', engineModels: ['N42', 'N46', 'N52', 'N54', 'N55', 'B48', 'B58'] },
    { name: 'MINI', slug: 'mini', landingPage: 'brands/mini.html', engineModels: ['N42', 'N46', 'N52', 'N54', 'N55', 'B48', 'B58'] },
  ],
  brandProducts: ['Engines', 'Gearboxes', 'Chassis Parts', 'Half-Cuts'],
  brands: ['Toyota', 'Honda', 'Nissan', 'Hyundai', 'Kia', 'BYD', 'Mitsubishi', 'Isuzu', 'Geely', 'Lexus', 'Hino', 'MG'],
};

window.ASIAPOWER = ASIAPOWER;
