/**
 * AsiaPower — Vehicle brand & model catalog for half-cut / VIN workflows
 * Self-contained; brand names match js/config.js brandsDirectory + Ssangyong + Isuzu.
 */
(function () {
  'use strict';

  /** @type {Record<string, string>} */
  const BRAND_SLUG = {
    'Toyota': 'toyota',
    'Lexus': 'lexus',
    'Honda': 'honda',
    'Acura': 'acura',
    'Nissan': 'nissan',
    'Infiniti': 'infiniti',
    'Mazda': 'mazda',
    'Mitsubishi': 'mitsubishi',
    'Subaru': 'subaru',
    'Suzuki': 'suzuki',
    'Daihatsu': 'daihatsu',
    'Hyundai': 'hyundai',
    'Kia': 'kia',
    'Genesis': 'genesis',
    'BYD': 'byd',
    'Geely': 'geely',
    'Zeekr': 'zeekr',
    'Lynk & Co': 'lynk-co',
    'Geometry': 'geometry',
    'Chery': 'chery',
    'Exeed': 'exeed',
    'Jetour': 'jetour',
    'Omoda': 'omoda',
    'Jaecoo': 'jaecoo',
    'Great Wall': 'great-wall',
    'Haval': 'haval',
    'Tank': 'tank',
    'Ora': 'ora',
    'MG': 'mg',
    'Roewe': 'roewe',
    'GAC': 'gac',
    'Changan': 'changan',
    'JAC': 'jac',
    'Dongfeng': 'dongfeng',
    'FAW': 'faw',
    'Foton': 'foton',
    'JMC': 'jmc',
    'Maxus': 'maxus',
    'Ford': 'ford',
    'Lincoln': 'lincoln',
    'Chevrolet': 'chevrolet',
    'GMC': 'gmc',
    'Buick': 'buick',
    'Cadillac': 'cadillac',
    'Volkswagen': 'volkswagen',
    'Audi': 'audi',
    'Skoda': 'skoda',
    'Seat': 'seat',
    'Mercedes-Benz': 'mercedes-benz',
    'BMW': 'bmw',
    'MINI': 'mini',
    'Porsche': 'porsche',
    'Ssangyong': 'ssangyong',
    'Isuzu': 'isuzu',
    // Added 2026-06-28 — confirmed via real VIN decode during inventory
    // correction (not previously in AsiaPower's catalog, no /brands/*.html yet).
    'Hawtai': 'hawtai',
    'Wuling': 'wuling',
    'Volvo': 'volvo',
    'Citroën': 'citroen',
    'Peugeot': 'peugeot',
    'Dodge': 'dodge',
    'Jeep': 'jeep',
    'Changan Kuayue': 'changan-kuayue',
    'Land Rover': 'land-rover',
    'Jaguar': 'jaguar',
    'Chrysler': 'chrysler',
    'Liebao': 'liebao',
    'Baojun': 'baojun',
  };

  /** Chinese display names for supplier / admin brand pickers */
  const BRAND_ZH = {
    'BYD': '比亚迪',
    'Geely': '吉利',
    'Zeekr': '极氪',
    'Lynk & Co': '领克',
    'Geometry': '几何',
    'Chery': '奇瑞',
    'Exeed': '星途',
    'Jetour': '捷途',
    'Omoda': '欧萌达',
    'Jaecoo': '捷酷',
    'Great Wall': '长城',
    'Haval': '哈弗',
    'Tank': '坦克',
    'Ora': '欧拉',
    'MG': '名爵',
    'Roewe': '荣威',
    'GAC': '广汽',
    'Changan': '长安',
    'JAC': '江淮',
    'Dongfeng': '东风',
    'FAW': '一汽',
    'Foton': '福田',
    'JMC': '江铃',
    'Maxus': '大通',
    'Hawtai': '华泰',
    'Wuling': '五菱',
    'Changan Kuayue': '长安跨越',
    'Land Rover': '路虎',
    'Jaguar': '捷豹',
  };

  const CHINESE_BRANDS = new Set(Object.keys(BRAND_ZH));

  /** @type {Record<string, string[]>} */
  const BRAND_MODELS = {
    'Toyota': [
      'Hilux',
      'Hilux Revo',
      'Hilux Vigo',
      'Land Cruiser',
      'Land Cruiser 70',
      'Land Cruiser 200',
      'Land Cruiser 300',
      'Land Cruiser Prado',
      'Fortuner',
      'Corolla',
      'Corolla Cross',
      'Camry',
      'RAV4',
      'Hiace',
      'Hiace Commuter',
      'Coaster',
      'Avanza',
      'Rush',
      'Innova',
      'Yaris',
      'Vios',
      'Alphard',
      'Vellfire',
      'Harrier',
      'C-HR',
      'Prius',
      'Sienna',
      'Tacoma',
      '4Runner',
      'FJ Cruiser',
      'Noah',
      'Voxy',
      'Estima',
      'Granvia',
      'Proace',
      'Dyna',
      'LiteAce',
    ],
    'Lexus': [
      'RX350',
      'RX450h',
      'LX570',
      'LX600',
      'GX460',
      'GX550',
      'NX200t',
      'NX300',
      'NX350',
      'ES250',
      'ES300h',
      'ES350',
      'IS250',
      'IS300',
      'IS350',
      'LS460',
      'LS500',
      'UX200',
      'UX250h',
      'RC350',
      'LC500',
      'LM350',
      'LM500h',
      'CT200h',
      'GS350',
      'RX300',
    ],
    'Honda': [
      'CR-V',
      'HR-V',
      'Accord',
      'Civic',
      'City',
      'Jazz',
      'Fit',
      'Pilot',
      'Odyssey',
      'BR-V',
      'WR-V',
      'Mobilio',
      'Freed',
      'Stream',
      'Stepwgn',
      'Vezel',
      'Passport',
      'Ridgeline',
      'Element',
      'Inspire',
      'Legend',
      'NSX',
      'Civic Type R',
      'Elevate',
    ],
    'Acura': [
      'MDX',
      'RDX',
      'TLX',
      'ILX',
      'Integra',
      'NSX',
      'ZDX',
      'RLX',
      'TSX',
      'TL',
      'RSX',
      'Legend',
      'CL',
      'SLX',
      'CDX',
      'EL',
      'CSX',
      'RL',
      'ZDX Type S',
    ],
    'Nissan': [
      'Navara',
      'Navara NP300',
      'Patrol',
      'Patrol Y62',
      'X-Trail',
      'Qashqai',
      'Tiida',
      'Sunny',
      'Almera',
      'Sentra',
      'Altima',
      'Teana',
      'Murano',
      'Pathfinder',
      'Kicks',
      'Juke',
      'Serena',
      'Elgrand',
      'Urvan',
      'NV350',
      'Caravan',
      'Frontier',
      'Titan',
      '370Z',
      'GT-R',
      'Leaf',
      'Note',
      'March',
      'Livina',
      'Terra',
      'Sylphy',
      'Cedric',
    ],
    'Infiniti': [
      'QX80',
      'QX60',
      'QX50',
      'QX55',
      'QX30',
      'Q50',
      'Q60',
      'Q70',
      'FX35',
      'FX37',
      'FX50',
      'EX35',
      'G35',
      'G37',
      'M35',
      'M37',
      'JX35',
      'QX70',
      'QX4',
      'I30',
      'I35',
    ],
    'Mazda': [
      'BT-50',
      'CX-3',
      'CX-5',
      'CX-8',
      'CX-9',
      'CX-30',
      'CX-60',
      'CX-90',
      'Mazda2',
      'Mazda3',
      'Mazda6',
      'MX-5',
      'Bongo',
      'Titan',
      'Demio',
      'Axela',
      'Atenza',
      'Premacy',
      'MPV',
      'Roadster',
      'CX-7',
      'Tribute',
      'B-Series',
      'Familia',
      'Capella',
    ],
    'Mitsubishi': [
      'Triton',
      'L200',
      'Pajero',
      'Pajero Sport',
      'Montero',
      'Outlander',
      'ASX',
      'Xpander',
      'Xpander Cross',
      'Mirage',
      'Attrage',
      'Lancer',
      'Galant',
      'Eclipse Cross',
      'Delica',
      'Fuso Canter',
      'Rosa',
      'Colt',
      'Space Star',
      'Strada',
      'Nativa',
      'Challenger',
      'Grandis',
      'i-MiEV',
      'Fuso Fighter',
    ],
    'Subaru': [
      'Forester',
      'Outback',
      'XV',
      'Crosstrek',
      'Impreza',
      'Legacy',
      'WRX',
      'WRX STI',
      'BRZ',
      'Levorg',
      'Ascent',
      'Tribeca',
      'Exiga',
      'Sambar',
      'Justy',
      'Baja',
      'Liberty',
      'SVX',
      'Alcyone',
      'Domingo',
    ],
    'Suzuki': [
      'Jimny',
      'Vitara',
      'Grand Vitara',
      'Swift',
      'Baleno',
      'Celerio',
      'Dzire',
      'Ertiga',
      'XL7',
      'APV',
      'Carry',
      'Every',
      'Alto',
      'Wagon R',
      'Ignis',
      'S-Cross',
      'SX4',
      'Kizashi',
      'Liana',
      'Escudo',
      'Super Carry',
      'Ciaz',
      'Splash',
      'Fronx',
      'Brezza',
    ],
    'Daihatsu': [
      'Terios',
      'Rocky',
      'Hijet',
      'Gran Max',
      'Luxio',
      'Xenia',
      'Sirion',
      'Mira',
      'Move',
      'Tanto',
      'Cast',
      'Thor',
      'Ayla',
      'Sigra',
      'Copen',
      'Charade',
      'Cuore',
      'Feroza',
      'Applause',
      'Be-go',
      'Boon',
      'Wake',
    ],
    'Hyundai': [
      'Tucson',
      'Santa Fe',
      'Elantra',
      'Sonata',
      'Accent',
      'i10',
      'i20',
      'i30',
      'Creta',
      'Venue',
      'Kona',
      'Palisade',
      'Staria',
      'H-1',
      'Grand Starex',
      'Starex',
      'Porter',
      'County',
      'Azera',
      'Genesis Coupe',
      'Veloster',
      'Ioniq',
      'Ioniq 5',
      'Ioniq 6',
      'Bayon',
      'Nexo',
      'Terracan',
      'Galloper',
      'Matrix',
      'Getz',
      'ix35',
      'Trajet',
    ],
    'Kia': [
      'Sportage',
      'Sorento',
      'Carnival',
      'Rio',
      'Cerato',
      'Forte',
      'Optima',
      'K5',
      'K2',
      'Picanto',
      'Stonic',
      'Seltos',
      'Telluride',
      'Mohave',
      'Bongo',
      'Pregio',
      'Soul',
      'Niro',
      'EV6',
      'EV9',
      'Carens',
      'Ceed',
      'Proceed',
      'Stinger',
      'Quoris',
      'K900',
      'Sonet',
      'Soluto',
      'Grand Carnival',
      'Spectra',
      'Pride',
    ],
    'Genesis': [
      'G70',
      'G80',
      'G90',
      'GV60',
      'GV70',
      'GV80',
      'Electrified G80',
      'Electrified GV70',
      'EQ900',
      'G90L',
      'G80 Sport',
      'GV80 Coupe',
      'G70 Shooting Brake',
      'GV70 Sport',
      'G90 Black',
      'GV60 Performance',
    ],
    'BYD': [
      'Han',
      'Tang',
      'Song',
      'Song Plus',
      'Song Pro',
      'Qin',
      'Qin Plus',
      'Yuan',
      'Yuan Plus',
      'Seal',
      'Dolphin',
      'Atto 3',
      'Seagull',
      'Destroyer 05',
      'F3',
      'F6',
      'G6',
      'S6',
      'S7',
      'e6',
      'T3',
      'M6',
      'Shark',
      'Leopard 5',
      'Leopard 8',
    ],
    'Geely': [
      'Coolray',
      'Azkarra',
      'Okavango',
      'Emgrand',
      'Emgrand X7',
      'Emgrand GT',
      'Boyue',
      'Tugella',
      'Monjaro',
      'Atlas',
      'Atlas Pro',
      'Geometry C',
      'Geometry A',
      'Preface',
      'Xingyue',
      'Binrui',
      'Borui',
      'Vision',
      'GC9',
      'MK',
      'LC',
      'Panda',
      'Icon',
      'Haoyue',
      'Xingrui',
    ],
    'Zeekr': [
      '001',
      '007',
      '009',
      'X',
      'Mix',
      '007 GT',
      '001 FR',
      '009 Grand',
      '007 Touring',
      '001 Shooting Brake',
      '009 Business',
      '007 Performance',
      '001 AWD',
      '009 AWD',
      'X AWD',
    ],
    'Lynk & Co': [
      '01',
      '02',
      '03',
      '03+',
      '05',
      '06',
      '08',
      '09',
      '01 PHEV',
      '05 PHEV',
      '03 Cyan',
      '02 Hatchback',
      '01 SUV',
      '09 EM-P',
      '08 EM-P',
    ],
    'Geometry': [
      'Geometry A',
      'Geometry C',
      'Geometry E',
      'Geometry G6',
      'Geometry M6',
      'Geometry EX3',
      'Geometry Panda Mini',
      'Geometry Firefly',
      'Geometry A Pro',
      'Geometry C Pro',
      'Geometry E Firefly',
      'Geometry G6 Pro',
      'Geometry M6 Pro',
      'Geometry EX5',
      'Geometry EX5 Pro',
    ],
    'Chery': [
      'Tiggo 2',
      'Tiggo 3',
      'Tiggo 4',
      'Tiggo 4 Pro',
      'Tiggo 5',
      'Tiggo 7',
      'Tiggo 7 Pro',
      'Tiggo 8',
      'Tiggo 8 Pro',
      'Arrizo 3',
      'Arrizo 5',
      'Arrizo 6',
      'Arrizo 8',
      'QQ',
      'Fulwin',
      'Eastar',
      'A5',
      'A3',
      'E5',
      'Exeed TX',
      'Omoda 5',
      'Jaecoo J7',
      'Tiggo 9',
      'Explore 06',
      'Windcloud',
      'Cowin',
    ],
    'Exeed': [
      'TX',
      'TXL',
      'VX',
      'LX',
      'RX',
      'Sterra ES',
      'Sterra ET',
      'Yaoguang',
      'Lingyun',
      'TXL Pro',
      'VX Pro',
      'LX Pro',
      'RX Pro',
      'Starfire',
      'Pegasus',
      'Exlantix ET',
    ],
    'Jetour': [
      'X70',
      'X70 Plus',
      'X90',
      'X90 Plus',
      'Dashing',
      'T2',
      'X95',
      'Shanhai L9',
      'Traveller',
      'X70 Coupe',
      'X70M',
      'X70S',
      'X90S',
      'Dasheng',
      'Fairy',
      'X70 Pro',
    ],
    'Omoda': [
      'C5',
      'C5 GT',
      'C7',
      'E5',
      'S5',
      'C5 EV',
      'C5 PHEV',
      'C5 Sport',
      'C5 Luxury',
      'C5 Comfort',
      'C5 Ultimate',
      'C5 Flagship',
      'C5 Cross',
      'C5 Urban',
      'C5 Premium',
    ],
    'Jaecoo': [
      'J7',
      'J8',
      'J6',
      'J5',
      'J7 PHEV',
      'J8 AWD',
      'J7 Urban',
      'J7 Adventure',
      'J8 Flagship',
      'J6 EV',
      'J5 Cross',
      'J7 Pro',
      'J8 Pro',
      'J7 GT',
      'J8 GT',
    ],
    'Great Wall': [
      'Wingle 5',
      'Wingle 6',
      'Wingle 7',
      'Steed',
      'Poer',
      'Poer King Kong',
      'Cannon',
      'Deer',
      'Safe',
      'Hover H3',
      'Hover H5',
      'Hover H6',
      'Hover M2',
      'Hover M4',
      'Florid',
      'Peri',
      'Cowry',
      'Voleex C30',
      'Voleex C50',
      'Pegasus',
      'Sing',
      'Sailor',
    ],
    'Haval': [
      'H1',
      'H2',
      'H3',
      'H4',
      'H5',
      'H6',
      'H6 GT',
      'H6 HEV',
      'H7',
      'H8',
      'H9',
      'Jolion',
      'F5',
      'F7',
      'F7x',
      'Big Dog',
      'Dargo',
      'M6',
      'M6 Plus',
      'Chitu',
      'Cool Dog',
      'H6 Coupe',
      'H2s',
      'Haval H6 PHEV',
      'Haval H9 Premium',
    ],
    'Tank': [
      'Tank 300',
      'Tank 400',
      'Tank 500',
      'Tank 700',
      'Tank 800',
      'Tank 300 City',
      'Tank 300 Adventure',
      'Tank 500 Hi4-T',
      'Tank 700 Hi4-T',
      'Tank 400 Hi4-T',
      'Tank 300 Diesel',
      'Tank 500 Premium',
      'Tank 300 Anniversary',
      'Tank 500 Luxury',
      'Tank 700 Ultra',
    ],
    'Ora': [
      'Good Cat',
      'Funky Cat',
      'Lightning Cat',
      'Punk Cat',
      'Ballet Cat',
      'Black Cat',
      'White Cat',
      'IQ',
      'R1',
      'R2',
      '03',
      '05',
      '07',
      'Good Cat GT',
      'Funky Cat GT',
    ],
    'MG': [
      'MG3',
      'MG4',
      'MG5',
      'MG6',
      'MG7',
      'MG HS',
      'MG ZS',
      'MG ZS EV',
      'MG RX5',
      'MG RX8',
      'MG Gloster',
      'MG Hector',
      'MG Hector Plus',
      'MG Astor',
      'MG One',
      'MG Cyberster',
      'MG Marvel R',
      'MG TF',
      'MG ZR',
      'MG ZT',
      'MG Extender',
      'MG GT',
      'MG Pilot',
      'MG Mulann',
      'MG Comet EV',
    ],
    'Roewe': [
      'RX5',
      'RX8',
      'RX3',
      'RX9',
      'i5',
      'i6',
      'i6 Max',
      'iMAX8',
      'Ei5',
      'Ei6',
      'Marvel X',
      'Marvel R',
      'W5',
      '550',
      '750',
      '360',
      '950',
      'Clever',
      'D7',
      'Whale',
      'FeiFan',
      'Vision-i',
      'RX5 Max',
      'RX5 Plus',
    ],
    'GAC': [
      'GS3',
      'GS4',
      'GS5',
      'GS7',
      'GS8',
      'GA3',
      'GA4',
      'GA5',
      'GA6',
      'GA8',
      'M6',
      'M8',
      'Aion S',
      'Aion Y',
      'Aion V',
      'Aion LX',
      'Trumpchi',
      'Empow',
      'GN8',
      'GN6',
      'Hyper GT',
      'Hyper SSR',
      'GS4 Plus',
      'GS8 Master',
    ],
    'Changan': [
      'CX20',
      'cx20',
      'CS35',
      'CS35 Plus',
      'CS55',
      'CS55 Plus',
      'CS75',
      'CS75 Plus',
      'CS85',
      'CS95',
      'Eado',
      'Eado Plus',
      'Alsvin',
      'UNI-T',
      'UNI-K',
      'UNI-V',
      'Hunter',
      'Kaicene F70',
      'Kaicene F30',
      'Oshan X5',
      'Oshan X7',
      'Lumin',
      'Benben',
      'Star Truck',
    ],
    'JAC': [
      'T6',
      'T8',
      'T9',
      'J2',
      'J3',
      'J4',
      'J5',
      'J6',
      'J7',
      'S2',
      'S3',
      'S4',
      'S5',
      'S7',
      'Refine',
      'Sunray',
      'N-Series',
      'X200',
      'iEV7S',
      'iEVA50',
      'Sehol A5',
      'Sehol X4',
      'Sehol QX',
      'Shuailing',
      'Kangling',
    ],
    'Dongfeng': [
      'Rich',
      'Rich 6',
      'Rich 7',
      'Fengon 500',
      'Fengon 580',
      'Fengon 330',
      'Fengon 370',
      'AX7',
      'AX3',
      'AX4',
      'AX5',
      'S30',
      'H30',
      'A30',
      'Aeolus Yixuan',
      'Aeolus Yixuan GS',
      'Aeolus Haohan',
      'Aeolus Haoji',
      'Paladin',
      'Oting',
      'Captain',
      'DFSK C-Series',
      'DFSK K-Series',
      'Glory 580',
      'Glory 330',
    ],
    'FAW': [
      'Besturn B30',
      'Besturn B50',
      'Besturn B70',
      'Besturn X40',
      'Besturn X80',
      'Besturn T77',
      'Besturn T99',
      'Besturn NAT',
      'Hongqi H5',
      'Hongqi H7',
      'Hongqi H9',
      'Hongqi HS5',
      'Hongqi HS7',
      'Hongqi E-HS9',
      'Hongqi L5',
      'Vita',
      'V2',
      'V5',
      'Oley',
      'Senia R7',
      'Senia S8',
      'Jiefang',
      'J6',
      'J7',
    ],
    'Foton': [
      'Tunland',
      'Tunland G7',
      'Tunland V9',
      'Sauvana',
      'View',
      'View CS2',
      'View G7',
      'View G9',
      'Toano',
      'Gratour',
      'Aumark',
      'Auman',
      'Forland',
      'Mars',
      'Thunder',
      'Sapir',
      'Midi',
      'Alpha',
      'G7',
      'G9',
      'EV Van',
      'Pickup',
      'Conqueror',
    ],
    'JMC': [
      'Vigus',
      'Vigus Pro',
      'Vigus Plus',
      'Boarding',
      'Carrying',
      'Yuhu',
      'Yuhu 3',
      'Yuhu 5',
      'Yuhu 7',
      'Yuhu 9',
      'Baodian',
      'Dadao',
      'Transit',
      'N800',
      'N900',
      'E-Series',
      'Kaiyun',
      'Shunda',
      'Fushun',
      'Isuzu D-Max',
      'Tourneo',
      'Conquer',
    ],
    'Maxus': [
      'T60',
      'T70',
      'T90',
      'D90',
      'D60',
      'G10',
      'G20',
      'G50',
      'G50 Plus',
      'V80',
      'V90',
      'V90C',
      'Deliver 9',
      'Deliver 7',
      'Deliver 3',
      'Euniq 5',
      'Euniq 6',
      'Mifa 9',
      'Terron 9',
      'Starship',
      'Interstellar',
      'EV30',
      'EV80',
      'Pickup',
    ],
    'Ford': [
      'Ranger',
      'Ranger Raptor',
      'Everest',
      'Explorer',
      'EcoSport',
      'Escape',
      'Focus',
      'Fiesta',
      'Mustang',
      'F-150',
      'F-250',
      'F-350',
      'Transit',
      'Transit Custom',
      'Tourneo Custom',
      'Territory',
      'Edge',
      'Fusion',
      'Mondeo',
      'Kuga',
      'Puma',
      'Bronco',
      'Bronco Sport',
      'Maverick',
      'Expedition',
      'Falcon',
      'Laser',
      'Telstar',
    ],
    'Lincoln': [
      'Navigator',
      'Aviator',
      'Nautilus',
      'Corsair',
      'MKX',
      'MKC',
      'MKT',
      'MKZ',
      'Continental',
      'Town Car',
      'Zephyr',
      'LS',
      'Blackwood',
      'Mark LT',
      'MKS',
      'Mark VIII',
      'Z',
    ],
    'Chevrolet': [
      'Colorado',
      'Trailblazer',
      'Captiva',
      'Trax',
      'Tracker',
      'Equinox',
      'Blazer',
      'Tahoe',
      'Suburban',
      'Silverado',
      'S10',
      'Spin',
      'Onix',
      'Prisma',
      'Cruze',
      'Malibu',
      'Impala',
      'Spark',
      'Aveo',
      'Sonic',
      'Orlando',
      'Traverse',
      'Camaro',
      'Corvette',
      'LUV D-Max',
      'N300',
      'N400',
      'Optra',
      'Lacetti',
    ],
    'GMC': [
      'Sierra',
      'Sierra HD',
      'Canyon',
      'Yukon',
      'Yukon XL',
      'Acadia',
      'Terrain',
      'Envoy',
      'Savana',
      'Safari',
      'Jimmy',
      'Typhoon',
      'Syclone',
      'Hummer EV',
      'Sierra Denali',
      'Yukon Denali',
      'Terrain Denali',
    ],
    'Buick': [
      'Enclave',
      'Encore',
      'Encore GX',
      'Envision',
      'Envista',
      'Regal',
      'LaCrosse',
      'Verano',
      'Excelle',
      'Excelle GT',
      'Excelle XT',
      'GL8',
      'GL6',
      'Century',
      'Park Avenue',
      'Riviera',
      'Skylark',
      'Rainier',
      'Terraza',
      'Lucerne',
    ],
    'Cadillac': [
      'Escalade',
      'Escalade ESV',
      'XT4',
      'XT5',
      'XT6',
      'CT4',
      'CT5',
      'CT6',
      'ATS',
      'CTS',
      'SRX',
      'XTS',
      'DTS',
      'STS',
      'DeVille',
      'Seville',
      'Eldorado',
      'Lyriq',
      'Celestiq',
      'Fleetwood',
      'Brougham',
    ],
    'Volkswagen': [
      'Amarok',
      'Tiguan',
      'Touareg',
      'Passat',
      'Jetta',
      'Golf',
      'Polo',
      'Virtus',
      'Vento',
      'Taos',
      'T-Cross',
      'T-Roc',
      'Atlas',
      'Teramont',
      'Transporter',
      'Crafter',
      'Caddy',
      'Multivan',
      'Caravelle',
      'Kombi',
      'Saveiro',
      'Fox',
      'Lavida',
      'Sagitar',
      'Bora',
      'Scirocco',
      'Touran',
      'Lamando',
      'Arteon',
      'ID.4',
      'ID.6',
    ],
    'Audi': [
      'Q2',
      'Q3',
      'Q5',
      'Q5 Sportback',
      'Q7',
      'Q8',
      'A1',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'Q3 Sportback',
      'e-tron',
      'e-tron GT',
      'TT',
      'R8',
      'RS3',
      'RS4',
      'RS5',
      'RS6',
      'RS7',
      'S3',
      'S4',
      'S5',
      'Allroad',
      'SQ5',
      'SQ7',
    ],
    'Skoda': [
      'Octavia',
      'Superb',
      'Fabia',
      'Rapid',
      'Kodiaq',
      'Karoq',
      'Kamiq',
      'Enyaq',
      'Yeti',
      'Roomster',
      'Scala',
      'Kushaq',
      'Slavia',
      'Felicia',
      'Favorit',
      'Citigo',
      'Praktik',
      'Forman',
      '120',
      '130',
      'Kodiaq RS',
      'Octavia RS',
      'Superb Combi',
    ],
    'Seat': [
      'Ibiza',
      'Leon',
      'Arona',
      'Ateca',
      'Tarraco',
      'Alhambra',
      'Toledo',
      'Cordoba',
      'Altea',
      'Exeo',
      'Mii',
      'Inca',
      'Marbella',
      'Malaga',
      'Ronda',
      'Cupra Formentor',
      'Cupra Born',
      'Cupra Leon',
      'Cupra Ateca',
      'Cupra Tavascan',
    ],
    'Mercedes-Benz': [
      'C200',
      'C300',
      'E200',
      'E300',
      'E350',
      'S350',
      'S450',
      'S500',
      'S600',
      'GLC250',
      'GLC300',
      'GLE350',
      'GLE450',
      'GLS450',
      'GLS600',
      'GLA200',
      'GLA250',
      'GLB200',
      'GLB250',
      'A180',
      'A200',
      'A250',
      'B180',
      'B200',
      'CLA200',
      'CLA250',
      'CLS350',
      'CLS450',
      'G350',
      'G500',
      'G63 AMG',
      'Sprinter',
      'Vito',
      'V-Class',
      'Actros',
      'Atego',
      'Unimog',
      'ML350',
      'GLK300',
      'R350',
    ],
    'BMW': [
      '320i',
      '320d',
      '325i',
      '330i',
      '330e',
      '520i',
      '520d',
      '530i',
      '530e',
      '540i',
      '730i',
      '740i',
      '750i',
      'X1',
      'X2',
      'X3',
      'X4',
      'X5',
      'X6',
      'X7',
      'XM',
      '118i',
      '120i',
      '218i',
      '220i',
      'M3',
      'M4',
      'M5',
      'M8',
      'Z4',
      'i3',
      'i4',
      'iX',
      'iX3',
      '116i',
      '318i',
      '335i',
      '428i',
      '435i',
    ],
    'MINI': [
      'Cooper',
      'Cooper S',
      'Cooper SE',
      'Countryman',
      'Clubman',
      'Paceman',
      'Convertible',
      'Hardtop',
      'John Cooper Works',
      'Cooper D',
      'One',
      'Cooper SD',
      'Countryman S',
      'Clubman S',
      'Electric',
      'Aceman',
      'Cooper Classic',
      'Cooper Sport',
    ],
    'Porsche': [
      '911',
      '911 Carrera',
      '911 Turbo',
      '911 GT3',
      '911 Targa',
      '718 Boxster',
      '718 Cayman',
      'Boxster',
      'Cayman',
      'Cayenne',
      'Cayenne Coupe',
      'Macan',
      'Macan GTS',
      'Panamera',
      'Panamera Sport Turismo',
      'Taycan',
      'Taycan Cross Turismo',
      'Cayenne S',
      'Cayenne Turbo',
      'Macan S',
      'Macan Turbo',
      '911 GT2 RS',
      '911 Dakar',
    ],
    'Ssangyong': [
      'Rexton',
      'Rexton Sports',
      'Rexton Sports Khan',
      'Korando',
      'Korando Sports',
      'Tivoli',
      'Tivoli XLV',
      'Musso',
      'Musso Grand',
      'Actyon',
      'Actyon Sports',
      'Kyron',
      'Rodius',
      'Stavic',
      'Chairman',
      'Torres',
      'Torres EVX',
      'XLV',
      'Korando e-Motion',
      'Rexton G4',
      'Musso Sports',
      'Actyon Turismo',
    ],
    'Isuzu': [
      'D-Max',
      'D-Max V-Cross',
      'D-Max Hi-Lander',
      'D-Max Spark',
      'MU-X',
      'MU-7',
      'Trooper',
      'Bighorn',
      'Rodeo',
      'Amigo',
      'VehiCROSS',
      'Wizard',
      'Faster',
      'KB',
      'Gemini',
      'Aska',
      'Florian',
      'Piazza',
      'Elf',
      'Forward',
      'Giga',
      'N-Series',
      'F-Series',
      'Traga',
      'Panther',
      'Crosswind',
    ],
    'Jeep': [
      'Grand Cherokee',
      'Cherokee',
      'Wrangler',
      'Compass',
      'Patriot',
      'Commander',
      'Renegade',
      'Gladiator',
      'Liberty',
      'Grand Wagoneer',
    ],
    'Land Rover': [
      'Range Rover',
      'Range Rover Sport',
      'Range Rover Evoque',
      'Range Rover Velar',
      'Discovery',
      'Discovery Sport',
      'Defender',
      'Freelander',
      'Freelander 2',
    ],
    'Jaguar': [
      'XJ',
      'XF',
      'XE',
      'F-PACE',
      'E-PACE',
      'I-PACE',
      'F-TYPE',
    ],
  };

  function brandToSlug(brand) {
    const key = String(brand || '').trim();
    if (BRAND_SLUG[key]) return BRAND_SLUG[key];
    return key.toLowerCase().replace(/\s+/g, '-');
  }

  function slugToBrand(slug) {
    const s = String(slug || '').trim().toLowerCase();
    const match = Object.entries(BRAND_SLUG).find(([, value]) => value === s);
    return match ? match[0] : '';
  }

  function getBrandLabel(name) {
    const brand = String(name || '').trim();
    const zh = BRAND_ZH[brand];
    return zh ? `${brand} · ${zh}` : brand;
  }

  function getBrandOptionGroups() {
    const chinese = [];
    const other = [];
    getBrandNames().forEach((name) => {
      if (CHINESE_BRANDS.has(name)) chinese.push(name);
      else other.push(name);
    });
    return { chinese, other };
  }

  function getBrands() {
    return Object.keys(BRAND_SLUG)
      .map((name) => ({ name, slug: BRAND_SLUG[name] }))
      .sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
  }

  function getBrandNames() {
    return getBrands().map((b) => b.name);
  }

  function mergeLearnedModels(map) {
    if (!map || typeof map !== 'object') return;
    Object.entries(map).forEach(([brand, models]) => {
      if (!Array.isArray(models)) return;
      models.forEach((model) => ensureModelOption(brand, model));
    });
  }

  function getModels(brandName) {
    const key = String(brandName || '').trim();
    const list = BRAND_MODELS[key];
    if (!list) return [];
    return list.slice().sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));
  }

  function ensureModelOption(brandName, modelName) {
    const brand = String(brandName || '').trim();
    const model = String(modelName || '').trim();
    if (!brand || !model) return model;
    if (!BRAND_MODELS[brand]) {
      BRAND_MODELS[brand] = [];
    }
    const existing = BRAND_MODELS[brand].find(
      (m) => m.toLowerCase() === model.toLowerCase()
    );
    if (existing) return existing;
    BRAND_MODELS[brand].push(model);
    BRAND_MODELS[brand].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));
    return model;
  }

  /**
   * Dynamically register a brand from QXB decode when it is missing from the
   * static catalog so supplier upload can select and save it.
   */
  function ensureBrandOption(brandName, options = {}) {
    const brand = String(brandName || '').trim();
    if (!brand) return '';
    const existingKey = Object.keys(BRAND_SLUG).find((name) => name.toLowerCase() === brand.toLowerCase());
    if (existingKey) return existingKey;

    const slug = String(options.slug || brandToSlug(brand)).trim() || brandToSlug(brand);
    BRAND_SLUG[brand] = slug;
    if (!BRAND_MODELS[brand]) BRAND_MODELS[brand] = [];
    if (options.zhLabel) {
      BRAND_ZH[brand] = String(options.zhLabel).trim();
      CHINESE_BRANDS.add(brand);
    }
    return brand;
  }

  window.VehicleCatalog = {
    BRAND_SLUG,
    BRAND_MODELS,
    BRAND_ZH,
    CHINESE_BRANDS,
    getBrands,
    getBrandNames,
    getBrandLabel,
    getBrandOptionGroups,
    getModels,
    mergeLearnedModels,
    brandToSlug,
    slugToBrand,
    ensureModelOption,
    ensureBrandOption,
  };
})();
