"""COO Reporter — generate short daily reports for CEO."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from tools import memory_tool, task_tool

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _recent_decisions(max_lines: int = 8) -> list[str]:
    return memory_tool.summarize_recent_decisions(max_lines)


def _next_action(summary: dict) -> str:
    if summary["blocked"]:
        blocked = summary["blocked"][0]
        return f"Unblock: {blocked['title']} ({blocked['id']})"

    urgent = summary.get("urgent_active") or []
    if urgent:
        t = urgent[0]
        return f"Prioritize: {t['title']} [{t['priority']}] → {t['owner_agent']}"

    pending = summary.get("pending") or []
    if pending:
        t = pending[0]
        return f"Start next: {t['title']} → {t['owner_agent']}"

    return "Review completed work and set next CEO goal with /plan."


def generate_daily_report() -> str:
    """Build daily COO report text and save to reports/daily_report_YYYY-MM-DD.md."""
    summary = task_tool.summarize_tasks()
    today = _today()
    decisions = _recent_decisions()
    next_action = _next_action(summary)

    lines = [
        f"# COO Daily Report — {today}",
        "",
        "## Task summary",
        f"- Total tasks: {summary['total']}",
        f"- Pending: {summary['by_status'].get('pending', 0)}",
        f"- In progress: {summary['by_status'].get('in_progress', 0)}",
        f"- Blocked: {summary['by_status'].get('blocked', 0)}",
        f"- Completed: {summary['by_status'].get('completed', 0)}",
        f"- Cancelled: {summary['by_status'].get('cancelled', 0)}",
        "",
        "## Pending tasks",
    ]

    if summary["pending"]:
        for t in summary["pending"][:10]:
            lines.append(f"- `{t['id']}` **{t['title']}** ({t['priority']}) → {t['owner_agent']}")
    else:
        lines.append("- (none)")

    lines.extend(["", "## Completed (recent)"])
    completed = summary.get("completed") or []
    if completed:
        for t in completed[-5:]:
            lines.append(f"- `{t['id']}` {t['title']}")
    else:
        lines.append("- (none)")

    lines.extend(["", "## Blocked"])
    if summary["blocked"]:
        for t in summary["blocked"]:
            lines.append(f"- `{t['id']}` {t['title']}")
    else:
        lines.append("- (none)")

    lines.extend(["", "## Recent decisions"])
    for d in decisions:
        lines.append(f"- {d.lstrip('# ').strip()}")

    lines.extend([
        "",
        "## Next recommended action",
        next_action,
        "",
        "---",
        f"*Generated by COO Reporter at {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
    ])

    report = "\n".join(lines)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORTS_DIR / f"daily_report_{today}.md"
    path.write_text(report + "\n", encoding="utf-8")
    return report
